name: Deploy jira-auth-server to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Поднимаем ssh-agent и загружаем ключ с passphrase
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

      # (опционально) добавим known_hosts, чтобы не отключать проверку
      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # rsync локальных файлов на сервер
      - name: Rsync to EC2
        run: |
          rsync -az --delete \
            --exclude='.git' --exclude='.github' \
            --exclude='**/__pycache__' --exclude='.venv' \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/jira-auth-server

      # Выполнить команды на сервере (установка зависимостей и рестарт сервиса)
      - name: Install deps & restart service
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<'EOF'
            set -e
            cd /opt/jira-auth-server
            if [ ! -d .venv ]; then python3 -m venv .venv; fi
            . .venv/bin/activate
            python -m pip install --upgrade pip wheel setuptools
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            elif [ -f pyproject.toml ]; then
              pip install .
            fi
            sudo systemctl restart jira-auth-server
            sudo systemctl --no-pager status jira-auth-server || true
          EOF

